GHP-Team-C/Capstone

package.json

Heres the database name and description

name and description

---

script/seed.js
server/db/index.js
server/db/models/Lesson.js
server/db/models/User.js
server/db/models/UserLesson.js

Ticket 12 & Ticket 15

---

package.json
webpack.config.js

fix: add babel-plugin-import to minimize mui's impact on webpack size

---

server/db/models/User.js

refactor: separate email & username in User model, add avatarUrl

---

script/seed.js

refactor: update seed file to match new models

---

client/features/lessons/LessonTemplate.js
client/features/lessons/MusicalStaff.js
client/features/lessons/StaffForm.js

refactor: rerender music staff without duplication

---

server/api/staves.js

refactor: activate model connection in staff get api

---

client/app/store.js
client/features/lessons/LessonTemplate.js
client/features/lessons/MusicalStaff.js
client/features/lessons/PianoKeys.js
client/features/lessons/StaffForm.js
client/features/lessons/lessonSlice.js
public/style.css
script/data/note.js
server/api/staves.js

Ticket 58contd

---

client/features/users/singleUserSlice.js

refactor: change fetchUser to fetchSingleUser

---

script/seed.js
server/db/index.js
server/db/models/Piano.js

feat: add piano to db

---

client/features/lessons/PianoKeys.js

feature: piano key labelling and notation

---

client/features/lessons/MusicalStaff.js

bugfix: change state.lesson to state.singleLesson in MusicalStaff

---

client/app/AppRoutes.js
client/features/lessons/lessonsSlice.js
client/features/navbar/Navbar.js
client/features/users/UserProfile.js
client/features/users/creatorDashboard.js
client/features/users/singleUserSlice.js
server/api/users.js

Ticket 61.1

---

client/features/lessons/MusicalStaff.js

feat: change notes to orange when actively selected

---

client/features/home/Home.js

fix: change /lessons navigate to new version

---

client/features/lessons/MusicalStaff.js

fix: change hardcoded music staff update ref to dynamic one

---

client/app/AppRoutes.js
client/features/auth/SignUpAuthForm.js
client/features/auth/authSlice.js

feature: signup for is up, authenticated, and saving on backend

Ticket 104

---

client/features/navbar/Navbar.js

refactor: change href in IconButton to links

---

client/features/lessons/LessonTemplate.js
client/features/lessons/PianoKeys.js
client/features/lessons/singleLessonSlice.js
script/seed.js
server/api/index.js
server/api/pianos.js
server/api/slides.js

feat: save user-indicated highlighted piano notes to database

---

client/features/lessons/LessonTemplate.js
client/features/lessons/singleLessonSlice.js
server/api/lessons.js

feature: buttons for new slides

Ticket 101

---

client/features/lessons/LessonTemplate.js

fix: give Publish button anonymous onclick handler

---

client/features/lessons/PianoKeys.js
server/api/lessons.js
server/db/models/Slide.js

fix: change pianoNotes to not try to render a note that doesn't exist

---

client/features/home/Home.js
client/features/navbar/Navbar.js

refactor: change href links to Links

---

client/features/users/UserLessonCard.js

feat: popup on Delete Lesson button working

---

client/features/lessons/LessonTemplate.js
client/features/lessons/singleLessonSlice.js
client/features/users/UserLessonCard.js
client/features/users/UserLessonsList.js
client/features/users/creatorDashboard.js
client/features/users/singleUserSlice.js
server/api/lessons.js
server/api/users.js

feat: hook up publish button on edit lesson view

---

client/features/users/UserLessonsList.js

fix: add closing div to UserLessonsList

---

client/features/lessons/CreateLesson.js
client/features/lessons/lessonsSlice.js
client/features/lessons/singleLessonSlice.js
server/api/lessons.js

Ticket 123

---

client/features/lessons/LessonTemplate.js
client/features/lessons/ViewLesson.js

feature: slide progress text in LessonTemplete when editing and View Lesson

feature: slide progress

---

client/features/lessons/LessonTemplate.js
client/features/lessons/LessonText.js
client/features/lessons/singleLessonSlice.js
script/seed.js
server/api/lessons.js

feat: add save title functionality to edit lesson

---

client/features/lessons/LessonTemplate.js
client/features/lessons/singleLessonSlice.js
server/api/slides.js

feat: add delete buttons for lesson and slide

---

client/features/lessons/LessonTemplate.js
client/features/lessons/LessonText.js
client/features/lessons/MusicalStaff.js

Ticket 164

---

client/features/auth/AuthForm.js
client/features/auth/SignUpAuthForm.js
client/features/auth/authSlice.js
client/features/home/Home.js

Fixed sign up page

---

client/features/navbar/Navbar.js

The dropdown for "User Profile" "Creater Dashboard" and Logout also adjusted "public Lessons" to "Lessons Feed"

Nav bar create button

---

client/features/lessons/LessonTemplate.js
client/features/lessons/LessonText.js

Ticket 180

---

client/features/home/Home.js
client/features/navbar/Navbar.js
client/index.js
public/index.html
public/style.css

Ticket 163

---

client/features/lessons/AllPublicLessons.js
client/features/lessons/ViewMusicalStaff.js
client/features/users/CreatorDashboard.js
client/features/users/UserLessonCard.js
client/features/users/UserProfile.js

Ticket 199
